---
author:
name: Sascha Credé
date: "2019-04-11"
title: Publications
---

<h2>&nbsp;Articles & conference contributions</h2>


Credé, S., Thrash, T., Hölscher, C., & Fabrikant, S. I. (2019). The advantageof globally visible landmarks for spatial learning. Journal of Environmental Psychology. doi: doi.org/10.1016/j.jenvp.2019.101369.

Thrash, T., Lanini-Maggi, S., Fabrikant, S. I., Bertel, S., Brügger, A., Credé,S.,  Do,  C.  T.,  Gartner,  G.,  Huang,  H.,  Münzer,  S.,  &  Richter,  K.-F.  (2019).The  Future  of  Geographic  Information  Displays  from  GIScience,  Carto-graphic,  and  Cognitive  Science  Perspectives  (Vision  Paper).  In  proceedings  of  the 14th  international  conference  on  spatial  information  theory. Dagstuhl, Germany. doi:10.4230/LIPIcs.COSIT.2019.19v

Credé, S., Thrash, T., Hölscher, C., & Fabrikant, S. I. (2019). The acquisitionof survey knowledge for local and global landmark configurations undertime pressure. Spatial Cognition & Computation, 19(3), 190–219. doi:10.1080/13875868.2019.1569016

Credé,  S.,  Thrash,  T.,  &  Fabrikant,  S.  I.  (2018).  The  effect  of  concurrenttask load on the acquisition of local and global landmark knowledge. Inspatial cognition 2018posters, book of abstracts. Center for Open Science, Inc. url: osf.io/4r5h6/

Credé, S. & Fabrikant, S. I. (2017). Let’s put the skyscrapers on the display – decoupling spatial learning from working memory. In international conference  on  spatial  information  theory  (pp.163–170).  Springer.  doi:  http://doi.org/10.1007/978-3-319-63946-8_31

Credé, S., Fabrikant, S. I., Thrash, T., & Hölscher, C. (2017). Do skyscrapers facilitate spatial learning under stress? On the cognitive processing of global landmarks. In International conference on spatial information theory (pp.27–29). Springer. doi: https://doi.org/10.1007/978-3-319-63946-8_7

Credé, S., Hölscher, C., & Frankenstein, J. (2014). Inferenzstrategien in Gebäuden:[Spatial Expectations in Indoor Environments]. In Abstracts of the 56th Conference of Experimental Psychologists (Vol. 56, pp. 49-49). Pabst Science.


<h2>&nbsp;Media communications</h2>


Digitale Pfadfinder (2017), Article in UZH Magazin.https://www.news.uzh.ch/de/articles/2017/Digitale-Pfadfinder.htmlEmotive (2017), 

Video for Digital Society Initiative.https://www.dsi.uzh.ch/de/research/projects/emotive.htmlTraining fürs "Bio-Navi" (2018), 

TV contribution on 3sat Nano.http://www.3sat.de/mediathek/?mode=play&obj=77292v
